### ISSUE TITLE
Web GUI

### ISSUE THREAD

**Issue by ptrcnull** [miscord/miscord#262]

**Comment by Vertmo** [comment]
Hi ! It would be a pleasure to help ! Are you planning to use [Express](https://expressjs.com/fr/) to make the website ? It's quite efficient and practical for a small web app like this

**Comment by Bjornskjald** [comment]
@Vertmo it's already work in progress at miscord/dashboard, but not published yet, I'll push an initial commit soon

**Comment by Vertmo** [comment]
Oh OK ! Well I'll keep an eye on that then !
