### ISSUE TITLE
Newly created channels should have no read permissions for the average Joe, only admins

### ISSUE THREAD

**Issue by simeonlg** [miscord/miscord#273]
**Describe the solution you'd like**
A facebook user private messages the bot, thus creating a new channel in Discord if the option to do so is enabled in the config. This newly created channel should only be seen by admins, who can then chose to make it publicly available if wanted.

**Describe alternatives you've considered**

**Additional context**
This makes it so that users who PM the bot user are still visible to the discord admins without needing to login to the bot account in a browser

**Comment by stanfear** [comment]
I would love this option, but not for only private messages, 
sometimes, a private channel is added to the bot, but not everyone on Discord should have access, right now, I have to manually wait for someone to post to have the possibility to set it to private.
