### ISSUE TITLE
Send Message when Attachments too Large

### ISSUE THREAD

**Issue by xLightAngel** [miscord/miscord#274]
Sometimes Miscord will DM me a message:

"DiscordAPIError: Request entity too large"

This usually happens when someone uploads a video that is too large for Discord to handle.

It would be awesome if Miscord could detect which user uploaded the attachment and we could customize a response message, that goes something like this:

"John Smith, your message was recognized, but your attachment is too large to be sent along the PokeLink network"

**Comment by PixelHir** [comment]
You say that this is enhancement, but sending too big attachment causes the whole bot to crash, so it should be marked a bug.

**Comment by Bjornskjald** [comment]
yeah @PixelHir, you're correct

**Comment by xLightAngel** [comment]
@PixelHir  When Discord blocks an attachment over 8 MB, this is not a bug... and nothing can be done about it

**Comment by Bjornskjald** [comment]
@xLightAngel well, it could not crash I guess...

**Comment by xLightAngel** [comment]
I forgot about the crashing part since I'm using 'pm2' to auto-restart...  my bad

**Comment by PixelHir** [comment]
Maybe simple try catch could solve the problem?

**Comment by Bjornskjald** [comment]
it already catches every error, the thing is to handle that error

**Comment by PixelHir** [comment]
Also, the following bug also applies to the message length.

**Comment by peteralynn** [comment]
xLightAngel or anyone, could you detail how you use pm2 to auto restart? I'm struggling on my own to figure it out...

**Comment by PixelHir** [comment]
@peteralynn Please refer to the [pm2 repo](https://github.com/Unitech/pm2).
This issue and repo is not supposed to be for this kind of help.

**Comment by Cyntech** [comment]
@peteralynn use systemctl instead, much easier. I'm using it and it's working fine:
https://stackoverflow.com/questions/4018154/how-do-i-run-a-node-js-app-as-a-background-service/29042953#29042953
