### ISSUE TITLE
showEvents doesn't work

### ISSUE THREAD

**Issue by RatingGull27** [miscord/miscord#275]
@Bjornskjald 
it not my showEvents when changing nickname on facebook messages with here logs for it 
[2018-07-27_04-07-44.log](https://github.com/Bjornskjald/miscord/files/2234421/2018-07-27_04-07-44.log)

**Comment by ajstewart** [comment]
Is this something that could be potentially fixed in the API or is currently impossible at that end?

**Comment by Bjornskjald** [comment]
I don't know, never really looked into it, but I think it can be fixed in the API.

**Comment by ajstewart** [comment]
Ok as that would be awesome if all these messages could pass through. Especially plan responses - that would be a huge addition (of course in terms of Pokemon Go).

**Comment by Bjornskjald** [comment]
@ajstewart @RatingGull27 is it still broken?

**Comment by RatingGull27** [comment]
@Bjornskjald yes is so broken

**Comment by RatingGull27** [comment]
hold

**Comment by RatingGull27** [comment]
@Bjornskjald no is not work so broken

**Comment by RatingGull27** [comment]
look like set to it looks like the setup like showevents: false other one showevents: true https://drive.google.com/open?id=1V7ZHJctT0uGF0gzOXwwDBbx0NpEiQLZe like this @Bjornskjald

**Comment by ajstewart** [comment]
Yeah I'm on 3.8.3, not all events come through. Only now and again do `X was added by Y` or nickname change messages come through (not all) but plan responses never do.

**Comment by RatingGull27** [comment]
@ajstewart https://github.com/miscord/miscord/issues/139

**Comment by ajstewart** [comment]
@RatingGull27 thanks for that I hadn't seen it before. Though plan responses is what I'm really after, that would be the fantastic.

**Comment by RatingGull27** [comment]
@Bjornskjald yes is broken when the new update for the miscord 3.10.0 the ShowEvents is not work

**Comment by Bjornskjald** [comment]
@RatingGull27 I know, that's why there's a label called **API issue**, because it's an issue with the API. There's nothing I could change in Miscord to make it work.

**Comment by Bjornskjald** [comment]
Waiting for `facebook-chat-api` contributors to fix it. (or I could take a try at it, but their codebase is so messy I don't want to touch it)
