### ISSUE TITLE
Multiple channels to one thread

### ISSUE THREAD

**Issue by nashultz** [miscord/miscord#284]
**Describe the solution you'd like**
I have tried to define two channels to go to the same facebook thread. Could you add support to allow the same facebook thread to recieve messages from 2 or more discord channels?

**Comment by PixelHir** [comment]
If one channel could receive messages from multiple channels, then where messages sent from Discord should be sent?

**Comment by Bjornskjald** [comment]
@PixelHir There are 2 possible solutions:
1. Messages from Channel A are sent to Channel B and FB thread
   Messages from Channel B are sent to Channel A and FB thread
2. Messages from Channel A are sent only to FB thread
   Messages from channel B are sent only to FB thread

**Comment by stanfear** [comment]
Yeah, and as a side effect, you could use it to sync 2 Discord channels, that would be fun !
