### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by PikaChewie82** [miscord/miscord#310]
I get an unexpected string in position 539.

**Comment by Bjornskjald** [comment]
Can I get the full error message? I have no idea what "position 539" is

**Comment by PikaChewie82** [comment]
I'm new to github so I'm probably doing something wrong.

**Comment by PikaChewie82** [comment]
Me either, lol. I will get it to you in the morning.

**Comment by PikaChewie82** [comment]
[https://imgur.com/a/Hfzsxs7](url)

Here is a screenshot of what I am seeing.

**Comment by Bjornskjald** [comment]
oh, unexpected string in JSON... so it's an issue with your config

**Comment by PikaChewie82** [comment]
what did I do wrong?

{
  "messenger": {
    "username": "my actual email@yahoo.com",
    "password": "my real password",
    "forceLogin": true,
    "whitelist": ["the actual string number"],
    "format": "*{username}*: {message}",
    "sourceFormat": {
      "discord": "(Discord)",
      "messenger": "(Messenger: {name})"
    },
    "ignoreEmbeds": true
  },
  "discord": {
    "token": "the real token",
   "renameChannels": false,
    "showFullNames": true
    "massMentions": true
  },
  "checkUpdates": false,
  "logLevel": "info",
}

Any idea what I might have wrong?

**Comment by Bjornskjald** [comment]
no comma after "showFullNames": true

**Comment by PikaChewie82** [comment]
and a comma after "loglevel": "info"

Thanks

**Comment by PikaChewie82** [comment]
okay, so it's running now, but nothing is happening when I write in either place. What did I miss?
