### ISSUE TITLE
Ignore messages containing substrings (Emoji)

### ISSUE THREAD

**Issue by simeonlg** [miscord/miscord#315]
**Describe the solution you'd like**
Do not send messages containing certain substrings. More specifically allow standalone emojis to be ignored. Custom discord emojis for a server for example are meaningless on messenger.

**Describe alternatives you've considered**
None

**Additional context**
For my use case it needs to be on a channel by channel basis. One chat/channel is used for reporting tasks, and sometimes users accidentaly click the messenger emoji with no option to remove it.

Could also possibly be tied in with picking up links and not sending them to avoid being softbanned by facebook

**Comment by fortepc** [comment]
I personally would like this not to happen, or at the very least have it a toggleable option. If emojis in Discord are named appropriately the people on the Discord side of the bridge can make some sort of heads or tails what it means. They're not totally meaningless.

**Comment by Bjornskjald** [comment]
of course togglable and configurable
