### ISSUE TITLE
v4.1.1 silent crashes Error: Connection closed

### ISSUE THREAD

**Issue by ajstewart** [miscord/miscord#331]
**Describe the bug**

Monitoring 4.1.1 today I was noticing that a few messages on Messenger were not making it through to Discord. Taking a look at the logs and pm2 restarts I see that the bot is being restarted often and when I look at the logs they only have the following:

```
[2018-10-13 04:55:51] Error: Connection closed.
    at TLSSocket.socket.on._ (/home/ec2-user/.npm-global/lib/node_modules/miscord/node_modules/libfb/dist/mqtt/MqttConnection.js:42:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:561:12)
    at TCP.done [as _onclose] (_tls_wrap.js:360:7)
```

I say this is silent because the error is not passed to the error channel (I can confirm that the error channel is working when I was testing things for issue #330).

Also oddly my logs in `~/.config/Miscord/logs/` are blank or only contain the error message. I wouldn't be surprised if this was something to do with my setup but is there possibly a logging issue?

**To Reproduce**

I'll note here that this is again with a large messenger group.

**Expected behavior**

For error to be reported (but also ideally not crash :P).

I think I will downgrade to 3.12.2 for now but before I do I am running 4.1.1 interactively to try and catch a crash log seeing as it seems all my logs are blank - I'll update once I get a crash (it really does seem to come from the large group, I can't get it to crash from my testing channel [4 people inc Miscord account]).

**Comment by Bjornskjald** [comment]
Related to ChatPlug/libfb-js#12

**Comment by Bjornskjald** [comment]
```
Also oddly my logs in ~/.config/Miscord/logs/ are blank or only contain the error message.
```
I was having the same issue and couldn't resolve it, I have no idea what causes it.

**Comment by ajstewart** [comment]
> ```
> Also oddly my logs in ~/.config/Miscord/logs/ are blank or only contain the error message.
> ```
> I was having the same issue and couldn't resolve it, I have no idea what causes it.

Ah ok - well, at least it's not just me I guess!
