### ISSUE TITLE
Sometimes picture attachments from Messenger do not get sent to Discord channel

### ISSUE THREAD

**Issue by banjoman05** [miscord/miscord#339]
**Describe the bug**
Occasionally a Facebook Messenger user will send a picture to the chat and that picture attachment will not be sent to the Discord channel. The text will be sent, however.

**Screenshots**
[One instance](https://i.imgur.com/bdqkfWb.png)

**Specifications:**
 - OS (VPS): Debian GNU/Linux 8.11 (jessie)
 - Miscord Version: 4.1.2 (also some previous versions but no verbose logs from then)
 - Node.js version: v8.12.0

**Additional context**
config.json:
<pre>
{
  "messenger": {
    "username": "USERNAME",
    "password": "PASSWORD",
    "whitelist": [
      "WHITELISTEDCHANNEL"
    ]
  },
  "discord": {
    "token": "BOT_TOKEN",
    "renameChannels": false,
    "showEvents": true
  },
  "timestamps": {
    "console": true
  },
  "channels": {
    "command": "CHANNEL",
    "error": "CHANNEL"
  },
  "logLevel": "silly",
  "timezone": "america/indiana/indianapolis"
}
</pre>

connections.yml:
<pre>
__comment: >-
  This is your connections.yml file. More info at
  https://github.com/miscord/miscord/wiki/Connections.yml
facebook-raid-chat:
  - type: discord
    id: 'CHANNELID'
    name: facebook-raid-chat
  - type: messenger
    id: 'MESSENGERID'
    name: Pokemon Go Raids
</pre>

I've enabled "silly" log verbosity and have the above instance available but will have to clean it up to post publicly. If I can be directed to which likely section of the ~3k lines the attachment failure occurs I could be grateful.

**Comment by Bjornskjald** [comment]
fixed, it was the "undefined" bug but it didn't send the message earlier
