### ISSUE TITLE
Facebook Messages Not Being Seen

### ISSUE THREAD

**Issue by Alolan-Mana** [miscord/miscord#359]
I've set up Miscord using the credentials for a dummy facebook account, and I have credated a bot in Discord to serve as the bridge per the instructions in the wiki. I've created my connections, and when I send messages from Discord, they appear in Facebook, but messages sent from Facebook do NOT appear in Discord. Strangely, if I change the chat name, it will pass that notification along.

I believe I have everything set up correctly, but I see this message in my audit channel:

Access token missing!
Error: Access token missing!
    at get.then.res (/usr/lib/node_modules/miscord/node_modules/libfb/dist/FacebookHttpApi.js:20:27)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

Where would I go to get what's missing here?

**Comment by RatingGull27** [comment]
@Alolan-Mana did you see the troubleshooting for it https://github.com/miscord/miscord/wiki/Troubleshooting
sometime it be discord bot token or not

**Comment by Bjornskjald** [comment]
nope @RatingGull27, it's a known bug.

**Comment by RatingGull27** [comment]
k

**Comment by Alolan-Mana** [comment]
Drat. Is there a way to get around this or maybe downgrade to another version that we can try?

**Comment by Bjornskjald** [comment]
Not yet, I'll try to work on it today, but I don't know if I'll be able to fix it.

**Comment by Alolan-Mana** [comment]
I appreciate your efforts on this Bjorn, good luck man!
