### ISSUE TITLE
Facebook account ban

### ISSUE THREAD

**Issue by morfikaa** [miscord/miscord#361]
Hi.
Help me pls.

In the last few days facebook banned 5 different accounts, although the newest version is running. Is there a solution for that?

thx,
m

**Comment by Bjornskjald** [comment]
Try to make your account as legit-looking as possible (eg. use real name/add a picture to it). Also, make sure nobody is reporting it as being fake.

The version has nothing to do with Facebook's bot detection algorithms.

**Comment by morfikaa** [comment]
It may be a problem that we do not synchronize 1 room, but 20?

**Comment by Bjornskjald** [comment]
Nope, I'm using almost 80 chats and it works fine. But... if the 20 chats have a large amount of messages coming to Facebook, try separating your chats between multiple accounts
