### ISSUE TITLE
Add Support for backup Facebook Accounts 

### ISSUE THREAD

**Issue by IamN0b0dy** [miscord/miscord#366]
Issue: Sometimes the Bot's FB account gets locked out forcing the bot down sometimes during peak usage. 

Proposed solution: Have the bot have a second and maybe a third FB account it can try to log into if the first FB account gets locked.

**Comment by vrokolos** [comment]
I'm trying to create a FB account for my bot but it always gets locked down by FB and requires a photo to validate it. Do you guys know of a way to bypass that?

**Comment by fortepc** [comment]
Allowing multiple accounts could also enable a type of load balancer.
