### ISSUE TITLE
Unable to open the app on a Mac

### ISSUE THREAD

**Issue by kyameel** [miscord/miscord#413]
I've installed Homebrew and downloaded the MacApp but I'm getting the following message. 

![screen shot 2019-02-18 at 10 13 15 am](https://user-images.githubusercontent.com/494425/52924074-ea78a780-3365-11e9-9a83-5cd76861b195.png)

# Expected Behavior
Able to open the MacApp link

# Specifications
Platform: Mac
OS: MacOs High Sierra 10.13.6 
App version: Miscord 4.7.1

**Comment by Bjornskjald** [comment]
It's a known issue, but I cannot reproduce it.
![obraz](https://user-images.githubusercontent.com/26630168/52993999-68948700-3416-11e9-8fe9-cc5f96bd960c.png)
![obraz](https://user-images.githubusercontent.com/26630168/52994032-82ce6500-3416-11e9-8c75-eee87a4dcb11.png)

**Comment by Bjornskjald** [comment]
Basically, I'm not a certified Apple Developer, so people would need to disable System Integrity Protection...

**Comment by gdude2002** [comment]
You could probably fundraise for this one.

**Comment by Bjornskjald** [comment]
It could be a Patreon goal, I guess.

**Comment by gdude2002** [comment]
$99 in a year should be doable, although I'd probably suggest a specific fundraiser, not necessarily Patreon

**Comment by faunam** [comment]
You should probably take down the link to download the app for mac on the miscord website. I just downloaded it and ran into the above issue.

**Comment by Bjornskjald** [comment]
damn, you're right
