### ISSUE TITLE
Use Nicknames instead of bot name.

### ISSUE THREAD

**Issue by MobbingAllDay** [miscord/miscord#427]
**Describe the solution you'd like**
Use nicknames instead of miscord. Like change nickname everytime it syncs messages so we can see whos typing instead of username: message

**Comment by Bjornskjald** [comment]
I can see two issues with it.
Firstly, the nickname updates on every message, so... even if you see who sent the last message, all the other ones would be sent by the same "person"
And secondly... it could generate a lot of spam.

**Comment by MobbingAllDay** [comment]
Right. Same pic but different "name".

**Comment by Bjornskjald** [comment]
Honestly, once tested, it's a really bad solution.
