### ISSUE TITLE
Let the bot account like some stuff or other activities to avoid getting flagged

### ISSUE THREAD

**Issue by simeonlg** [miscord/miscord#432]
Liking some pictures and friending people seems to help with avoiding bans and/or verification processes. If the bot could do this on its own, it could provide a longer life for the bot accounts.

**Describe alternatives you've considered**
Manually providing interaction

**Additional context**
Manual interaction may trigger suspicious login activity

**Comment by Bjornskjald** [comment]
You mean, bot behaving more like a bot could make it not look like a bot? :thinking: 

With all seriousness though, we don't have access to Facebook APIs so there's no way of coding something like that, not to mention how complex it would be :slightly_frowning_face:
