### ISSUE TITLE
Miscord loops after updating to v5.0.2

### ISSUE THREAD

**Issue by justandras** [miscord/miscord#441]
**Describe the bug**
Miscord loops after updating to v5.0.2. It doesn't find package.json.

**To Reproduce**
1. Update or install the latest version
2. Try to run it

You get it.

**Expected behavior**
It starts

**Screenshots**
![image](https://user-images.githubusercontent.com/32372119/65831104-21c51480-e2b6-11e9-85f4-00877bd66f78.png)

**Specifications:**
 - Raspbian 9.6

 - Version:
5.0.2

 - Node.js version:
10.12.0

**Comment by Bjornskjald** [comment]
Fixed in https://github.com/miscord/miscord/pull/442/commits/6db5b0cc7222e2c11744e6fd564dd4817294a87f.
