### ISSUE TITLE
Miscord dashboard miscellaneous tab doesn't save data

### ISSUE THREAD

**Issue by nileplumb** [miscord/miscord#444]
Data isn't saved when entering command error channels or timezone data on the misc tab.

miscord 5.0.3 docker version

**Comment by kamieniarz** [comment]
Same here on Ubuntu 18.4 LTS

**Comment by Bjornskjald** [comment]
What browsers are you using?

**Comment by nileplumb** [comment]
Firefox and Chrome

**Comment by kamieniarz** [comment]
Chrome

**Comment by Bukowskaii** [comment]
Dug thru this a bit, looks like the property channels.error doesn't exist in the data array before its initially set to the data being passed into the "deseralize" function is 'undefinied'. either need to change `dotProp.get(data,field.id)` method to return empty string when the field.id doesn't exist in the data array, (load.js line 9) or `field.value = data.join('\n')` to check for data being undefined before running join (deserialize.js line 6)

**Comment by Bukowskaii** [comment]
changing line 6 in deserialize.js to below should fix the issue

`if (type === 'textarea') field.value = data ? data.join('\n') : ''`

**Comment by ptrcnull** [comment]
For being extra safe I would add `data instanceof Array` to make sure it has a `join` method

**Comment by Bukowskaii** [comment]
@ptrcnull even better :)
