### ISSUE TITLE
Config Generator to support multiple accounts

### ISSUE THREAD

**Issue by simeonlg** [miscord/miscord#445]
As added in https://github.com/miscord/miscord/commit/25b7185283d2fdee9d4f328075103deb6fe317b0#diff-55587a4496721b5abbba188fa44de898

**Comment by glensc** [comment]
The referred commit. how do you actually use it, how do you map which account to which channel? and the diff is weird, it just logs in all account ts but does not store any result anywhere.

**Comment by ptrcnull** [comment]
First of all, that's not related to the issue.
Second of all, you don't, the feature's purpose was to provide backup accounts with the same chats, so if one account fails, it can fall back to the other one. As you can see [here](https://github.com/miscord/miscord/commit/25b7185283d2fdee9d4f328075103deb6fe317b0#diff-d179c7ef798b482037f79dec8ff42771R42), there's a `for` loop iterating over all the accounts and saving the Messenger client object to a variable called `client` from the upper scope. The loop stops when... okay, at this point I realized that the loop doesn't actually stop. I'll create another issue for that.

**Comment by glensc** [comment]
x-ref for the issue: https://github.com/miscord/miscord/issues/468
