### ISSUE TITLE
Game status to display Facebook login status 

### ISSUE THREAD

**Issue by simeonlg** [miscord/miscord#446]
**Describe the solution you'd like**
The status of the bot could display if the Facebook side is up and running, letting regular users know if the bridge to Facebook is offline. 

Ex: "Logged in to Facebook"

**Describe alternatives you've considered**
Allow read access to the miscord command channel to everyone, but this is not a desirable solution.

**Additional context**
Perhaps also customized in some way? Or at least toggle in config

Example from another bot
```
client.on("ready", () => {
  client.user.setActivity(config.prefix + config.command);
});
```

**Comment by ptrcnull** [comment]
Fixed back in August 2019 with status color:

https://github.com/miscord/miscord/commit/62b9fb54e54ea844ebfad494e1470909ba85287f
