### ISSUE TITLE
Can't not bypassing facebook checkpoint 

### ISSUE THREAD

**Issue by lenhattruong165** [miscord/miscord#450]

**Comment by lenhattruong165** [comment]
I am login so many times and try many ways . event login on browser for the code
It still din't login on terminal

**Comment by lenhattruong165** [comment]
> I am login so many times and try many ways . event login on browser for the code

**Comment by glensc** [comment]
the bug report is useless and should be closed

**Comment by ptrcnull** [comment]
There are some guides for bypassing Facebook checkpoints (or just making them less frequent), check the Discord server for more details: https://discord.gg/DkmTvVz
