### ISSUE TITLE
msg->dsc bridging broken if msg channel name is longer than 100 chars

### ISSUE THREAD

**Issue by selfisekai** [miscord/miscord#455]
**Describe the bug**
miscord doesn't send bridge any messages from messenger to discord if channel name is over 100 characters.

**To Reproduce**
1. change the conversation name to something with over 100 characters
2. send any message

**Expected behavior**
truncate the name before applying to channel or don't change it.

**Screenshots**
```
Invalid Form Body
name: Must be between 1 and 100 in length.
DiscordAPIError: Invalid Form Body
name: Must be between 1 and 100 in length.
    at /usr/local/lib/node_modules/miscord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /usr/local/lib/node_modules/miscord/node_modules/snekfetch/src/index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Specifications:**
 - OS: debian (docker image miscord/miscord `sha256:eb17fed16906a11f0c72df65208ab0124ef08130c388b67dcfae303f006f7d66`)

 - Version: 5.0.4

 - Node.js version: 13.4.0

**Additional context**
example breaking name: `KONIEC KURWA NASZEJ ZAGŁADY BO FECTKA OD MATMY W 85% ŹLE OBLICZYŁA DELTE KORONAWIRUSA I JĄ ZNALAZŁ (TYLKO SPOKÓJ MOŻE NAS URATOWAĆ)`

**Comment by ptrcnull** [comment]
Thanks for reminding me, I'll try to fix it in a few days

**Comment by ptrcnull** [comment]
...and it only took me a month.
Still faster than Miscord v5, I guess.
