### ISSUE TITLE
Miscord Website

### ISSUE THREAD

**Issue by mrufflesmcghie** [miscord/miscord#461]
Miscord Website SSL expired no access to documentation

**Comment by ptrcnull** [comment]
Docs are on https://docs.miscord.net/, with certificate expiring on 9th of October, but thanks for the reminder 😅

**Comment by mrufflesmcghie** [comment]
docs.miscord.net works fine
miscord.net showing error

**Comment by ptrcnull** [comment]
Yeah, I know, I'll fix this in a matter of seconds

**Comment by ptrcnull** [comment]
Updated, it should be okay now.
