### ISSUE TITLE
Add showing Messenger Plans

### ISSUE THREAD

**Issue by RighteousPotato** [miscord/miscord#87]
When creating/updating/responding to a plan on FBM nothing gets posted to Discord. The bot console session shows it is receiving these events but doing nothing with them.

In a perfect world:
- Creating a plan on FBM creates an embed on Discord (And maybe pins the message..?)
- Embed shows plan name, location, date and numbers confirmed as going/not going
- Changes made in FBM update the existing embed on Discord.

**Comment by Bjornskjald** [comment]
I'll see if that's possible (if [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api) has a functionality to listen for event changes).

**Comment by RighteousPotato** [comment]
That's a shame - sounds like the functionality is there once they fix it though.

**Comment by Bjornskjald** [comment]
Update: https://github.com/Schmavery/facebook-chat-api/pull/608#issuecomment-372362626
So... it's possible, but requires changes in facebook-chat-api to fetch plan data.

**Comment by RighteousPotato** [comment]
So with the fix they've merged in now does it just not crash any more but still can't see details?

**Comment by Bjornskjald** [comment]
Yup, that's right. It's impossible to see the details without another request with event ID.

**Comment by Bjornskjald** [comment]
@ajstewart see #275, there's an issue with Facebook API

**Comment by ajstewart** [comment]
In case anyone is desperate, inspired by the duct tape over a hole in a boat solution for polls in #139 I've written a similar solution for plan messages.

Like that solution I do not really know json so I'm sure it could be done far better, but it seems to work and does what I want it to.

Follow the instructions in #139 - edit the file:

`miscord\node_modules\facebook-chat-api\src\listen.js`

Go to line 240 or so where it should say `case "delta":` and paste the code below - be sure to change your timezone!

But again this is not a 'fix', just a temporary solution!

```
var eventdeltas = ['lightweight_event_update_time',
                   'lightweight_event_update_title',
                   'lightweight_event_delete',
                   'lightweight_event_create',
                   'lightweight_event_notify',
                   'lightweight_event_rsvp'
                    ];
if (eventdeltas.indexOf(v.delta.type) > -1)
{
    var eventinfo = "-------------------------------------------------------\n_**" + 
    v.delta.messageMetadata.adminText + "**" + '\n\n**Plan information:**\n';
    var event = JSON.parse(v.delta.untypedData.guest_state_list);
    var going = 0;
    var declined = 0;
    // created plans do not have event_title
    if (v.delta.type != 'lightweight_event_create')
    {
        var event_title = v.delta.untypedData.event_title;
        if (event_title == "") {event_title = "Plan not named!"}
    }
    else 
    {
        var event_title = "New plan!"
    }
    eventinfo = eventinfo + "Name: " + event_title + "\n"
    var event_time = Number(v.delta.untypedData.event_time);
    var dateTime = new Date(event_time* 1000);
    var options = { weekday: "long", day:"2-digit", month: "long", hour:"2-digit", minute:"2-digit",
                     timeZone: 'Australia/Sydney', localeMatcher:"lookup"}
    var formatted = dateTime.toLocaleString("en-GB", options);
    eventinfo = eventinfo + "Time: " + formatted + "\n"
    for (i in event)
    {
        var status = event[i].guest_list_state;
        if (status == "GOING") {going+=1}
        else if (status == "DECLINED") {declined+=1}
    }
    eventinfo = eventinfo + "Going: "+JSON.stringify(going)+"\nDeclined: "+JSON.stringify(declined)+"_";
    eventinfo = eventinfo + "\n-------------------------------------------------------"
    v.delta = {
    attachments:[],
    body: eventinfo,
    irisSeqID: v.delta.irisSeqID,
    messageMetadata: v.delta.messageMetadata,
    ttl: v.delta.ttl,
    class: 'NewMessage'
    }
    
}
```

![edit-plans](https://user-images.githubusercontent.com/3306161/45553652-d640f380-b877-11e8-98b6-08d597527717.png)

**Comment by Bjornskjald** [comment]
@ajstewart I could try to integrate it into facebook-chat-api by reviewing this code you wrote, maybe slightly improving it and publishing as a PR to facebook-chat-api

**Comment by Bjornskjald** [comment]
or... I can just create my own fork of facebook-chat-api with these changes and add it to miscord until it's added to the main (Schmavery's) repository

**Comment by ajstewart** [comment]
@Bjornskjald yeah I was wondering what the aim of the API was in this case. As even if you got the status messages you still couldn't see the plan details such as numbers attending. If the code is a helping start I'm happy for it to propagate to the facebook-chat-api.

It sounds like your own branch might give more freedom of fixing things quicker but then you run the danger of diverging too much I guess. I think I'll leave that up to you!

I would be interested to see an improved version! I struggled with the time string a bit, couldn't get it how I wanted, mostly there in the end. Also the IDs of the facebook users are also there so you could even put a list of actual attendees. I wasn't sure how to get the names so I left it (you can see their response message anyway).

**Comment by Bjornskjald** [comment]
oh, I have an idea, I could make the plan message pinned and edit it with new "going"/"can't go" info

**Comment by ajstewart** [comment]
Yeah that could work, that would be pretty sweet. You’d have to listen out for other changes too like title, time etc but that should be easy.

If you want to go really far you could add emoticons to the pinned message and then when a Discord user clicks on that emotion an automatic message is posted saying that Discord user wants to join the plan (as if from them) e.g. “Discord user @{user} responded going to {plan name}”. That’s probably as close as an integration you could get!

**Comment by Bjornskjald** [comment]
Damn, the biggest problem would be timezones. Another field in the config?

**Comment by ajstewart** [comment]
I think that would be simple enough to include in the config, though you would have to state clearly that there is a set list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
